Footer TOS
timjedrek/penn-air-repair pull request #1
Opened 2024-03-14 19:10 UTC by raminka13

- [x] Footer Info and TOS.
- [x] Route for TOS.
- [x] Text replace "Simplifly" for "Penn Air Repair", but is a FS TOS Text.
- [x] TOS header color change.

2024-03-15 03:27 UTC, timjedrek requested changes
Please revise TOS.

2024-03-15 03:27 UTC, timjedrek commented on app/views/pages/tos.html.erb
<img width="978" alt="image" src="https://github.com/timjedrek/penn-air-repair/assets/67489728/7901928a-32ac-4506-a97b-f9efe7f85629">

Penn Air repair is not a flight school in Mesa / Spanish fork.. It's a aviation maintenance provider in Pottstown, PA.

2024-03-15 18:10 UTC, raminka13 commented
- [x] Changes made on TOS, colors, links and text.
- [x] bottom_footer change.

2024-03-19 08:36 UTC, timjedrek approved these changes

2024-03-19 08:36 UTC, merged